version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:3001
      - NEXT_PUBLIC_ENVIRONMENT=development
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - AVALANCHE_FUJI_RPC_URL=https://api.avax-test.network/ext/bc/C/rpc
      - TELEPORTER_CONTRACT_ADDRESS=0x253b2784c75e510dD0fF1da844684a1aC0aa5fcf
    volumes:
      - ./backend:/app
      - /app/node_modules

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    profiles:
      - production

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: icm-dashboard-network